//go:build ignore

// Command gen_android_policy writes ../android_policy_test.go: Android's app
// seccomp allowlist for arm64 and x86_64, as syscall numbers, derived from
// bionic's policy inputs in ./bionic the way AOSP's genseccomp.py does
// (allowed = SYSCALLS + allowlists + priority − blocklists).
//
//	cd server && go run ./cmd/engine/testdata/gen_android_policy.go
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// arches maps a Go GOARCH to its bionic arch name and x/sys syscall table.
var arches = []struct{ goarch, bionic, table string }{
	{"amd64", "x86_64", "zsysnum_linux_amd64.go"},
	{"arm64", "arm64", "zsysnum_linux_arm64.go"},
}

const dir = "cmd/engine/testdata/bionic"

func main() {
	xsys, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "golang.org/x/sys").Output()
	if err != nil {
		log.Fatal(err)
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by testdata/gen_android_policy.go from bionic's seccomp\n" +
		"// policy inputs (testdata/bionic). DO NOT EDIT.\n\n//go:build linux\n\npackage main\n\n" +
		"// androidAppAllowlist is Android's app seccomp allowlist, by GOARCH.\n" +
		"var androidAppAllowlist = map[string][]uint32{\n")
	for _, a := range arches {
		numbers := sysnums(filepath.Join(strings.TrimSpace(string(xsys)), "unix", a.table))
		allowed := map[string]bool{}
		for _, f := range []string{"SYSCALLS.TXT", "SECCOMP_ALLOWLIST_COMMON.TXT", "SECCOMP_ALLOWLIST_APP.TXT"} {
			for _, n := range names(f, a.bionic) {
				allowed[n] = true
			}
		}
		for _, n := range priority() {
			allowed[n] = true
		}
		for _, f := range []string{"SECCOMP_BLOCKLIST_COMMON.TXT", "SECCOMP_BLOCKLIST_APP.TXT"} {
			for _, n := range names(f, a.bionic) {
				delete(allowed, n)
			}
		}
		var nums []int
		var unknown []string
		for n := range allowed {
			if nr, ok := numbers[n]; ok {
				nums = append(nums, nr)
			} else {
				unknown = append(unknown, n)
			}
		}
		sort.Ints(nums)
		sort.Strings(unknown)
		if len(unknown) > 0 {
			// Names the kernel doesn't define for this arch (bionic lists a few
			// arch-generic ones); they can't be called, so there's nothing to allow.
			log.Printf("%s: no syscall number for %v", a.goarch, unknown)
		}
		fmt.Fprintf(&out, "\t%q: {", a.goarch)
		for i, n := range nums {
			if i > 0 {
				out.WriteString(", ")
			}
			fmt.Fprint(&out, n)
		}
		out.WriteString("},\n")
	}
	out.WriteString("}\n")
	src, err := format.Source(out.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("cmd/engine/android_policy_test.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}

var sysnumRe = regexp.MustCompile(`^\s*SYS_([A-Z0-9_]+)\s*=\s*(\d+)`)

func sysnums(path string) map[string]int {
	f, err := os.Open(path)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	m := map[string]int{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		if g := sysnumRe.FindStringSubmatch(sc.Text()); g != nil {
			var n int
			fmt.Sscan(g[2], &n)
			m[strings.ToLower(g[1])] = n
		}
	}
	return m
}

// names returns the kernel syscall names a policy file lists for arch.
func names(file, arch string) []string {
	f, err := os.Open(filepath.Join(dir, file))
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	var out []string
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		open, close := strings.Index(line, "("), strings.LastIndex(line, ")")
		if open < 0 || close < open {
			continue
		}
		if !archMatches(strings.TrimSpace(line[close+1:]), arch) {
			continue
		}
		// func[|aliases][:syscall[:socketcall_id]]
		head := line[:open]
		name := strings.SplitN(head, "|", 2)[0]
		if parts := strings.Split(head, ":"); len(parts) > 1 {
			name = parts[1]
		}
		out = append(out, strings.TrimSpace(name))
	}
	return out
}

func archMatches(list, arch string) bool {
	for _, a := range strings.Split(list, ",") {
		switch strings.TrimSpace(a) {
		case "all", "lp64", arch:
			return true
		}
	}
	return false
}

func priority() []string {
	data, err := os.ReadFile(filepath.Join(dir, "SECCOMP_PRIORITY.TXT"))
	if err != nil {
		log.Fatal(err)
	}
	var out []string
	for _, l := range strings.Split(string(data), "\n") {
		if l = strings.TrimSpace(l); l != "" && !strings.HasPrefix(l, "#") {
			out = append(out, l)
		}
	}
	return out
}
