package jsjson

import (
	"encoding/json"
	"os"
	"strconv"
	"testing"
)

// numbers.json / strings.json are generated by the TypeScript core
// (JSON.stringify golden output); see the PR that introduced the Go port.

func TestNumberStringMatchesJSONStringify(t *testing.T) {
	data, err := os.ReadFile("testdata/numbers.json")
	if err != nil {
		t.Fatal(err)
	}
	var pairs [][2]string
	if err := json.Unmarshal(data, &pairs); err != nil {
		t.Fatal(err)
	}
	for _, pair := range pairs {
		f, err := strconv.ParseFloat(pair[0], 64)
		if err != nil {
			t.Fatalf("parse %q: %v", pair[0], err)
		}
		if got := NumberString(f); got != pair[1] {
			t.Errorf("NumberString(%v) = %q, JS says %q", f, got, pair[1])
		}
	}
}

func TestStringEscapingMatchesJSONStringify(t *testing.T) {
	data, err := os.ReadFile("testdata/strings.json")
	if err != nil {
		t.Fatal(err)
	}
	var pairs [][2]string
	if err := json.Unmarshal(data, &pairs); err != nil {
		t.Fatal(err)
	}
	for _, pair := range pairs {
		if got := string(Stringify(pair[0])); got != pair[1] {
			t.Errorf("Stringify(%q) = %q, JS says %q", pair[0], got, pair[1])
		}
	}
}

func TestStringifyOrderedObject(t *testing.T) {
	o := NewObj()
	o.Set("z", 1.0)
	o.Set("a", nil)
	o.Set("nested", []any{true, "x"})
	got := string(Stringify(o))
	want := `{"z":1,"a":null,"nested":[true,"x"]}`
	if got != want {
		t.Errorf("got %s want %s", got, want)
	}
}

func TestStringifyIndentMatchesJSONStringifyLayout(t *testing.T) {
	inner := NewObj()
	inner.Set("a", 1.0)
	o := NewObj()
	o.Set("k", inner)
	o.Set("arr", []any{1.0})
	o.Set("empty", []any{})
	got := string(StringifyIndent(o, 2))
	want := "{\n  \"k\": {\n    \"a\": 1\n  },\n  \"arr\": [\n    1\n  ],\n  \"empty\": []\n}"
	if got != want {
		t.Errorf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestParsePreservesKeyOrderAndRoundTrips(t *testing.T) {
	src := `{"b":1,"a":{"y":2.5,"x":null},"list":[{"q":1e+21},"s"]}`
	v, err := Parse([]byte(src))
	if err != nil {
		t.Fatal(err)
	}
	if got := string(Stringify(v)); got != src {
		t.Errorf("round-trip: got %s want %s", got, src)
	}
}
